### ISSUE TITLE
Alexa Thermostat Support

### ISSUE THREAD

**Issue by mrzackzadek** [NorthernMan54/homebridge-alexa#120]
Still would KILL for thermostat support for Alexa.  Brought it up on Reddit as well... Thanks so much!!

**Comment by NorthernMan54** [comment]
I saw that comment on reddit, and this is on my list, but will need to find some time in the future.

**Comment by rodalpho** [comment]
Would that include air conditioner support as well? 

I have a crappy (but free!) smart air conditioner dongle from ThinkECO that can _ONLY_ be controlled via its terrible app or a homebridge plugin, no third-party Home, Alexa, or Google support. I'm trying to bridge it from Apple Home to Alexa in a shameful Frankenstein's monster abomination.

**Comment by mrzackzadek** [comment]
@rodalpho that's exactly the use I need it for as well!  Hahaha - that first-party app is SO awful that home bridge has been a lifesaver...it works fantastically...but Alexa support would be game changing.

Thank you @NorthernMan54 for considering it...!

**Comment by fazerize** [comment]
`[2018-11-8 08:36:36] [Alexa] _alexaThermostatController missing action SetTargetTemperature Unexpected token u in JSON at position 0 { ReportState: '[{"interface":"Alexa.TemperatureSensor","host":"192.168.178.101","port":51826,"aid":12,"iid":11},{"interface":"Alexa.ThermostatController","host":"192.168.178.101","port":51826,"aid":12,"iid":12}]' }
  alexaLocal WARNING - Bad response message [ { field: 'data',
    message: 'no (or more than one) schemas match',
    value: { event: [Object] },
    type: undefined,
    schemaPath: [] } ] +13ms
  alexaLocal ---------------------------- Request -------------------------------- +1ms
  alexaLocal {"directive":{"header":{"namespace":"Alexa.ThermostatController","name":"SetTargetTemperature","payloadVersion":"3","messageId":"d968db70-f30e-4357-8de4-fa806d0855db","correlationToken":"AAAAAAAAAQD4MLBmU2lrqdC9lJIB745iDAIAAAAAAACdFKLIhTW8FYe2lczUSNg/8Pf6PR5f9TIF4EdB+r1JWKxkSlrTANNSOgivN/cQ+f01J1MzCR6TzK+wXowuwryd8fsl6sufv5tnh7eAczCzlm35fVAERQKPj1oGe8UPIzT4uylet67NXum4aDvd6mO7zzFgqSw/lShIw+N1YfeIvXK5xm2QKFg6zz7OelHweuIUaG0WKmPk2ak6xeUEzyvSqkUwhcHjp4UQbqwnRiVP91lKg4TtWha13qAJUMkRD/Q6NQQ4LltIlxjgE4f+lt9yxh29B+DkHRMIbAzFfhSQLVkUow0V6z46FyOn8gYr8g9zw73iLPOnF7eyHUE9cTZSPAG1x/Na7fL10SsuKBqR+Td5EYr4fkIijHEw1CeGd+iMcNXWaVyWv095ENjMvNeVHtHem4CGAdaqDrIhQK0xTLv+8IIZ6IX/ZgzmG85+BpCRFP0HqQU2uwCx+e6lPs3z82PEoH9deSbLj/XaDY9utbtIglmtppkMJW5W4a8qZPftr8lHP1+rW6xiLK8buPke9Ejwqkm+rqdoHpZwFrXPrSZ2IrzTDCSMN/LdOAYZqr547NxEs78czBU04g1xS+gaGGoBi1zc7yAHiPy1hDOiqND137mpX/wmzsTnW9jqeWe/eJO8r2iaUW+c3fBGwsIASTZ4spwXuzbevwFGUblNOwg0iqYRlgWPzHyKHg=="},"endpoint":{"endpointId":"MTkyLjE2OC4xNzguMTAxOjUxODI2LGFpZDogMTIsaWlkOiAxNQ==","cookie":{"ReportState":"[{\"interface\":\"Alexa.TemperatureSensor\",\"host\":\"192.168.178.101\",\"port\":51826,\"aid\":12,\"iid\":11},{\"interface\":\"Alexa.ThermostatController\",\"host\":\"192.168.178.101\",\"port\":51826,\"aid\":12,\"iid\":12}]"}},"payload":{"targetSetpoint":{"value":22.5,"scale":"CELSIUS"}}}} +1ms
  alexaLocal ---------------------------- Response ------------------------------- +3ms
  alexaLocal {"event":{"header":{"name":"ErrorResponse","namespace":"Alexa.ThermostatController","payloadVersion":"3","messageId":"d968db70-f30e-4357-8de4-fa806d0855db"},"payload":{"endpoints":[]}}} +0ms
  alexaLocal ------------------------------------------------------------ +1ms`

Thats my current error. Whats the reason?

**Comment by NorthernMan54** [comment]
This error is a result of the cookie name for set target temperature.   When the action comes in from Alexa it is looking for a cookie based on the action, which in this case is SetTargetTemperature.   In alexatranslator, please change the cookie name, and ensure that the supplied AID and IID are mapped to the correct HomeKit characteristic.

**Comment by fazerize** [comment]
i did ... just read my edit

**Comment by NorthernMan54** [comment]
With thanks to @fazerize we now have initial support for thermostats.  Now the feature is extremely
limited, and only only allows setting target temperature, in celsius.  Please update to version 0.1.60 and try again

**Comment by hmangnx** [comment]
Is it me or it still doesn’t discover my SmartAC unit yet...? Any updates?

**Comment by NorthernMan54** [comment]
If you have updated to the most recent version of the plugin, it should include something for HomeKit Thermostats.  How well it works is not known as the mapping between Alexa and HomeBridge is not complete.

**Comment by hmangnx** [comment]
It’s interesting because I am not sure what this considered. Possibly an Air-conditioner?

Supposedly they are adding Alexa support sometime “soon” but it would be so awesome to be able to just turn this on and off.

It works via Siri because of homebridge. 

[https://ibb.co/R6bqkmB](url)

**Comment by NorthernMan54** [comment]
Your using homebridge-platform-smartac ? I looked at this plugin and it should work fine.  Are you running the latest homebridge-alexa plugin?

**Comment by hmangnx** [comment]
Yes I am running that plugin and it works fine. But when I tell Alexa to discover it doesn’t find it. I sees my tplink smart plug though. And I am running the latest one I believe by running npm install -g homebridge-alexa...

**Comment by NorthernMan54** [comment]
When you are saying recent, I assume that is within the last 2 or 3 days and that you haven’t installed it twice?  Once with sudo and once without?

**Comment by hmangnx** [comment]
I installed it a few days ago and then removed it because I thought it wouldn’t work until I read the GitHub then I decided to try it again this morning. So the install was fresh this morning.

**Comment by NorthernMan54** [comment]
Your account is “hmangnx”?

**Comment by hmangnx** [comment]
Yes that is my account, I’ll run a debug and let you know what it shows.

**Comment by hmangnx** [comment]
Hmm, how do I run this debug command when my homebridge is installed on a windows machine...

**Comment by hmangnx** [comment]
Ok I figured it out here you go:

C:\WINDOWS\system32>set DEBUG=* & homebridge -I
[2018-11-28 21:03:34] Loaded config.json with 0 accessories and 3 platforms.
[2018-11-28 21:03:34] ---
[2018-11-28 21:03:34] Loaded plugin: homebridge-alexa
[2018-11-28 21:03:34] Registering platform 'homebridge-alexa.Alexa'
[2018-11-28 21:03:34] ---
[2018-11-28 21:03:35] Loaded plugin: homebridge-platform-smartac
[2018-11-28 21:03:35] Registering platform 'homebridge-platform-smartac.SmartAC'
[2018-11-28 21:03:35] ---
[2018-11-28 21:03:35] Loaded plugin: homebridge-tplink-smarthome
[2018-11-28 21:03:35] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[2018-11-28 21:03:35] ---
[2018-11-28 21:03:35] Loading 3 platforms...
[2018-11-28 21:03:35] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[2018-11-28 21:03:35] [TplinkSmarthome] homebridge-tplink-smarthome v3.11.0, node v8.9.4, homebridge v0.4.45
[2018-11-28 21:03:35] [ThinkEco SmartAC Platform] Initializing SmartAC platform...
[2018-11-28 21:03:35] [Alexa] Initializing Alexa platform...
[2018-11-28 21:03:35] Loading 0 accessories...
[2018-11-28 21:03:35] [TplinkSmarthome] Configuring cached accessory: [Christmas Tree] 8006D64F4196F79DA4240219BA083B6D1770D715 10cb33b3-e397-463c-b0fe-3ecc01ca9324
  alexaHAP Starting Homebridge instance discovery +0ms
  alexaLocal Connecting to Homebridge Smart Home Skill +3ms
[2018-11-28 21:03:35] [ThinkEco SmartAC Platform] api updating thermostat status...
[2018-11-28 21:03:35] [ThinkEco SmartAC Platform] api logging in...
  alexaHAP HAP Device discovered Smart Bridge 2 [ '192.168.1.166', 'fe80::8230:dcff:fe70:a781' ] +172ms
  alexaHAP HAP instance address: Smart Bridge 2 -> Lutron-8030dc70a781.local -> 192.168.1.166 +3ms
[2018-11-28 21:03:35] [TplinkSmarthome] New Device Online: [Christmas Tree] plug [8006D64F4196F79DA4240219BA083B6D1770D715] 192.168.1.194 9999
[2018-11-28 21:03:35] [TplinkSmarthome] Adding: [Christmas Tree] plug [8006D64F4196F79DA4240219BA083B6D1770D715]
  alexaHAP HAP Discover failed Smart Bridge 2 http://192.168.1.166:4548 error code 470 +24ms
  alexaLocal error { Error: connect ECONNREFUSED 35.169.132.61:8883
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '35.169.132.61',
  port: 8883 } +1s
  alexaLocal offline +6ms
[2018-11-28 21:03:38] [ThinkEco SmartAC Platform] Initializing platform accessory 'PTAC'...
Setup Payload:
X-HM://0023ISYWYO011

 EventedHTTPServer Server listening on port 51826 +0ms
[2018-11-28 21:03:38] Homebridge is running on port 51826.
  alexaHAP HAP Device discovered Homebridge-CAD8 [ 'fe80::65e3:cc4f:bf3f:d1b1',
  '192.168.1.29',
  'fe80::8cc8:c420:fc17:b300',
  '192.168.137.1' ] +3s
  alexaHAP HAP instance address: Homebridge-CAD8 -> CC_22_3D_E3_CE_30.local -> 192.168.1.29 +4ms
  EventedHTTPServer [::ffff:192.168.1.29] New connection from client +980ms
  EventedHTTPServer [::ffff:192.168.1.29] HTTP server listening on port 56975 +2ms
  EventedHTTPServer [::ffff:192.168.1.29] HTTP request: /accessories +7ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.1.29] HTTP Response is finished +4ms
  alexaHAP Homebridge instance discovered Homebridge-CAD8 with 3 accessories +31ms
  EventedHTTPServer [::ffff:192.168.1.29] Client connection closed +5ms
  EventedHTTPServer [::ffff:192.168.1.29] HTTP connection was closed +2ms
  EventedHTTPServer [::ffff:192.168.1.29] HTTP server was closed +2ms
  EventedHTTPServer [::ffff:192.168.1.181] New connection from client +15ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP server listening on port 56978 +1ms
  EventedHTTPServer [::ffff:192.168.1.178] New connection from client +5ms
  EventedHTTPServer [::ffff:192.168.1.178] HTTP server listening on port 56979 +2ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP request: /pair-verify +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +4ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP Response is finished +12ms
  EventedHTTPServer [::ffff:192.168.1.178] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.1.178] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP request: /pair-verify +19ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:30] Client AC8A0F3E-841F-463B-86A9-9F9E0800697C verification complete +2ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.178] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:30] Client AC8A0F3E-841F-463B-86A9-9F9E0800697C verification complete +3ms
  EventedHTTPServer [::ffff:192.168.1.178] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP request: /accessories +3ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.178] HTTP request: /accessories +7ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +2ms
  EventedHTTPServer [::ffff:192.168.1.178] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.18] New connection from client +5ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP server listening on port 56982 +1ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.223] New connection from client +2ms
  EventedHTTPServer [::ffff:192.168.1.223] HTTP server listening on port 56984 +1ms
  EventedHTTPServer [::ffff:192.168.1.223] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +1ms
EventedHTTPServer [::ffff:192.168.1.223] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP request: /pair-verify +5ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:30] Client AC8A0F3E-841F-463B-86A9-9F9E0800697C verification complete +1ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP request: /accessories +4ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.223] HTTP request: /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +2ms
  HAPServer [CC:22:3D:E3:CE:30] Client 7CACF0BB-934F-4E02-827E-6B312FFFAB6E verification complete +1ms
  EventedHTTPServer [::ffff:192.168.1.223] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:192.168.1.223] HTTP request: /accessories +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.1.223] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP request: /characteristics +174ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +2ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true},{"aid":3,"iid":11,"ev":true},{"aid":3,"iid":12,"ev":true},{"aid":3,"iid":13,"ev":true},{"aid":3,"iid":14,"ev":true}] +2ms
  Accessory [Homebridge] Registering Characteristic "Active" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Current Heater Cooler State" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Target Heater Cooler State" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Current Temperature" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Cooling Threshold Temperature" for events +1ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP request: /characteristics +10ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":11,"ev":true},{"aid":2,"iid":12,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Outlet In Use" for events +0ms
  EventedHTTPServer [::ffff:192.168.1.181] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.1.178] HTTP request: /characteristics +151ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +3ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true},{"aid":3,"iid":11,"ev":true},{"aid":3,"iid":12,"ev":true},{"aid":3,"iid":13,"ev":true},{"aid":3,"iid":14,"ev":true}] +2ms
  Accessory [Homebridge] Registering Characteristic "Active" for events +2ms
  Accessory [Homebridge] Registering Characteristic "Current Heater Cooler State" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Target Heater Cooler State" for events +2ms
  Accessory [Homebridge] Registering Characteristic "Current Temperature" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Cooling Threshold Temperature" for events +2ms
 EventedHTTPServer [::ffff:192.168.1.178] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:192.168.1.178] HTTP request: /characteristics +10ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +2ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":11,"ev":true},{"aid":2,"iid":12,"ev":true}] +4ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Outlet In Use" for events +2ms
  EventedHTTPServer [::ffff:192.168.1.178] HTTP Response is finished +1ms
  alexaLocal reconnect +2s
  alexaLocal connect command/hmangnx/# +38ms
  alexaLocal Emitting Alexa.Discovery +13s
  alexaTranslator Alexa Controllable Homebridge-CAD8 1 +8ms
[2018-11-28 21:03:54] [Alexa] alexaDiscovery - returned 1 devices
  alexaLocal Emitting Alexa.Discovery +440ms
  alexaTranslator Alexa Controllable Homebridge-CAD8 1 +2ms
[2018-11-28 21:03:54] [Alexa] alexaDiscovery - returned 1 devices
  alexaLocal Emitting Alexa.Discovery +825ms
  alexaTranslator Alexa Controllable Homebridge-CAD8 1 +1ms
[2018-11-28 21:03:55] [Alexa] alexaDiscovery - returned 1 devices
  EventedHTTPServer [::ffff:192.168.1.18] HTTP request: /characteristics +45s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +3ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":11,"ev":true},{"aid":2,"iid":12,"ev":true}] +3ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Outlet In Use" for events +2ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP request: /characteristics +13ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +2ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true},{"aid":3,"iid":11,"ev":true},{"aid":3,"iid":12,"ev":true},{"aid":3,"iid":13,"ev":true},{"aid":3,"iid":14,"ev":true}] +2ms
  Accessory [Homebridge] Registering Characteristic "Active" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Current Heater Cooler State" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Target Heater Cooler State" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Current Temperature" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Cooling Threshold Temperature" for events +1ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.1.18] HTTP request: /characteristics?id=3.12,3.14,3.13,3.10,3.11 +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /characteristics?id=3.12,3.14,3.13,3.10,3.11 +1ms
  Accessory [Homebridge] Getting value for Characteristic "Target Heater Cooler State" +2ms
  Accessory [Homebridge] Got Characteristic "Target Heater Cooler State" value: 2 +4ms
  EventedHTTPServer [::ffff:192.168.1.181] Sending HTTP event '3.12' with data: {"characteristics":[{"aid":3,"iid":12,"value":2}]} +2ms
  EventedHTTPServer [::ffff:192.168.1.178] Sending HTTP event '3.12' with data: {"characteristics":[{"aid":3,"iid":12,"value":2}]} +2ms
  EventedHTTPServer [::ffff:192.168.1.18] Muting event '3.12' notification for this connection since it originated here. +1ms
  Accessory [Homebridge] Getting value for Characteristic "Cooling Threshold Temperature" +1ms
  Accessory [Homebridge] Getting value for Characteristic "Current Temperature" +1ms
  Accessory [Homebridge] Getting value for Characteristic "Active" +1ms
  Accessory [Homebridge] Getting value for Characteristic "Current Heater Cooler State" +1ms
[2018-11-28 21:04:26] [ThinkEco SmartAC Platform] api updating thermostat status...
[2018-11-28 21:04:27] [ThinkEco SmartAC Platform] PTAC get target temp: 60
  Accessory [Homebridge] Got Characteristic "Cooling Threshold Temperature" value: 15.5 +2s
  EventedHTTPServer [::ffff:192.168.1.181] Sending HTTP event '3.14' with data: {"characteristics":[{"aid":3,"iid":14,"value":15.5}]} +1ms
  EventedHTTPServer [::ffff:192.168.1.178] Sending HTTP event '3.14' with data: {"characteristics":[{"aid":3,"iid":14,"value":15.5}]} +3ms
  EventedHTTPServer [::ffff:192.168.1.18] Muting event '3.14' notification for this connection since it originated here. +2ms
[2018-11-28 21:04:27] [ThinkEco SmartAC Platform] PTAC current temp: 70
  Accessory [Homebridge] Got Characteristic "Current Temperature" value: 21.1 +4ms
  EventedHTTPServer [::ffff:192.168.1.181] Sending HTTP event '3.13' with data: {"characteristics":[{"aid":3,"iid":13,"value":21.1}]} +2ms
  EventedHTTPServer [::ffff:192.168.1.178] Sending HTTP event '3.13' with data: {"characteristics":[{"aid":3,"iid":13,"value":21.1}]} +8ms
  EventedHTTPServer [::ffff:192.168.1.18] Muting event '3.13' notification for this connection since it originated here. +2ms
[2018-11-28 21:04:27] [ThinkEco SmartAC Platform] PTAC heating / cooling active: true

**Comment by NorthernMan54** [comment]
Looking at the log, I see that homebridge-alexa successfully retrieved 3 accessories from your homebridge instance, but only passed 1 up to Alexa.

I’m still thinking it is an old version of homebridge-alexa in your environment causing the issue.  Are you 100% sure you are running version 0.1.61 or greater?

**Comment by hmangnx** [comment]
How can I check to make sure? Or I can always uninstall and reinstall.

**Comment by hmangnx** [comment]
I removed and reinstalled it and it shows 0.1.62. Still no go...

**Comment by NorthernMan54** [comment]
Okay, I put a unix shell script in the plugins tools directory called dump_accessories, that takes a single command line argument ip:port ie 127.0.0.1:51826, and outputs all the details of your accessories.  As your on Windows I don't know how to run it, but it uses the curl command to call homebridge.  If you have curl or an equivalent on windows, you should be able to just copy and paste it

https://github.com/NorthernMan54/homebridge-alexa/blob/master/tools/dump_accessories

**Comment by NorthernMan54** [comment]
@fazerize I have the first draft of Thermostat control with Mode ready for testing. The following features should be fully enabled

1 - Changing modes between HEAT, COOL, AUTO and OFF
2 - Set a new target temperature

For these changes I'm using a special version of the plugin to ensure that everything works okay prior to releasing to the world, so please follow these instructions to install the special version.

https://github.com/NorthernMan54/homebridge-alexa/issues/201#issuecomment-480307601

Also, if you have not updated your plugin version recently, I made a major change about a month ago that causes all devices to be lost, and you need to discover again. Please take this into account before installing.

**Comment by NorthernMan54** [comment]
This is now fully supported in the main version
