### ISSUE TITLE
Alexa miss the all device everytime the DHCP lease is renewed.

### ISSUE THREAD

**Issue by gaojie429** [NorthernMan54/homebridge-alexa#185]
The proble is as titled.

Everytime the DHCP lease is renewed, when I say to alexa "turn on my device", alexa say "the device isn't responding ".
This is the log when this error occurred.
`ERROR: alexaStateResponse connect EHOSTDOWN 10.0.0.31:51826 - Local (10.0.0.51:61011)`.
I think this is caused by the change of IP address, and now I use static IP.
However, I don't want use static IP, so I want you to add the option that use the {hostname}.local instead of IP on config.json.

**Comment by NorthernMan54** [comment]
@gaojie429 How often is your DHCP lease expiring?   

You should be able to ask Alexa to 'Discover Devices' and she should update the ip address automatically.  ( Also Amazon does a refresh/Discover Devices about every 6 hours )

If you are ending up with Duplicate's/offline devices I have updated the device unique naming logic in a new feature branch I'm working on.  Details are here:

https://github.com/NorthernMan54/homebridge-alexa/tree/event#beta-test-for-sending-events-to-alexa-and-using-in-routines

PS During the design phase, I made a decision to have all communications use the IP address rather than hostname for performance concerns.  In some scenarios local resolution of hostname's can take an extended amount of time, and cause 'Not responding' responses from Alexa.

For my  homebridge servers, I have gone into my Router and and added them as a DHCP Static Lease  rather than a static IP to avoid these issues.

**Comment by gaojie429** [comment]
@NorthernMan54 
My DHCP lease is renewed every 4 hours.
> You should be able to ask Alexa to 'Discover Devices' and she should update the ip address automatically. ( Also Amazon does a refresh/Discover Devices about every 6 hours )
OK, I'll try to ask her it and set the DHCP lease expiring frequency to longer than 6 hours.
If those don't help me, then I'll checkout the your new feature.

> PS During the design phase, I made a decision to have all communications use the IP.....
I see, I didn't know that there are technical problems that cause 'not responding' issue in name resolution.

Thank you for your hardworking !!
