### ISSUE TITLE
homebridge.ca - why?

### ISSUE THREAD

**Issue by wiresio** [NorthernMan54/homebridge-alexa#196]
Sorry if I missed some information: Why is it necessary that there is a man-in-the-middle i.e. homebridge.ca? I feel a bit uncomfortable about this.

**Comment by NorthernMan54** [comment]
If you review this, Amazon includes the required deployment architecture, and in their terms you could think of homebridge.ca as "Smart Device Manufacturer Cloud".

The actual implementation looks like this

https://github.com/NorthernMan54/alexaAwsBackend#end-to-end-design


https://developer.amazon.com/docs/smarthome/understand-the-smart-home-skill-api.html

**Comment by wiresio** [comment]
Thanks for the information. I now feel even more uncomfortable! There's two layers in between including a link to Google Analytics. Who is controlling and maintaining them?

**Comment by NorthernMan54** [comment]
@wiresio Please take a moment and review the Amazon document, the 2 layers are part of their model and the why’s are explained there.  In regards to google analytics usage, it is not your typical user tracking use case it’s being used for, but for error monitoring and error trending.  Rather than build my own error monitoring dashboard, I just use their analytics dashboard and rather than track page views etc, I’m tracking failed and successful service messages, so I have visibility when things go wrong without having to watch log files etc in real time.  Dashboard looks like this

![DB8C4135-11B2-46A5-B198-3C52E071C163](https://user-images.githubusercontent.com/19808920/54819288-d3cdb500-4c71-11e9-8859-d6f2ea8cec8d.png)

In regards to who, this is just me running this as a hobby and as a free service, and I’m not some mega corporation offering this. Please keep in mind this is all open source, so your welcome to review. And if you still feel uncomfortable, please feel free to make your own.

**Comment by wiresio** [comment]
Thanks for your detailed explanation! To be clear: I highly appreciate your work and am definitely not able to do that on my own. So also many thanks for that!
About homebridge.ca: Despite the trust and security aspects (which are probably well covered) you as the maintainer have to take care that it is always up-to-date and up-and-running. Just as a hobby that might turn out to be an excessive task. So my comment goes in the direction whether there is maybe another option taking that pressure from you and transfering it to e.g. Amazon directly.

**Comment by NorthernMan54** [comment]
Sorry Amazon doesn't offer that type of service.

**Comment by sschuste** [comment]
Thanks for the explanations. I like the idea that this could be part of the README. While I find it odd that I might feel uncomfortable after already chasing my data (and others') through the iCloud or Alexa or wherever, many people are interested in what exactly happens to data they have generated themselves. Living in Europe, where data protection laws are strict, you often would like more transparency in this data processing. You could start with that as a good example for everyone else :-D

**Comment by NorthernMan54** [comment]
@sschuste @wiresio I would gladly accept a pull request for that content if you wanted to wordsmith it into something more presentable for users. 

And for the other comment on monitoring, I'm not sure if your aware, but I'm using Homebridge's Slack for real time monitoring, and have uptime-robot providing alerts in real-time to the channel #hap-alexa

As it has been running with 100% availability for the longest time, the fact that it is there may be not visible to people. The last unplanned service disruption was back on Feb 14th, and was down for a 1 minute.

https://stats.uptimerobot.com/2WmEDHyV6
