### ISSUE TITLE
Design or Process flow help

### ISSUE THREAD

**Issue by svenkat86** [NorthernMan54/homebridge-alexa#24]
Hi,
First of all Thank you for your contribution and the entire setup worked for me on both iphone and alexa devices. I am not sure if i can raise it as a issue, but still wanted to bring it up here.
Is it possible to get a design or process flow on the alexa interactions? I understand the part where alexa converts voice commands to requests, but how is that converted request reaching my raspberry pi which is running locally. From what i understand, alexa talks to cloud api and then it trigger events on local if you have a port open (something like ngrok). Can you share at high level, how you are achieving this communication here. 

Thanks in advance,
Venkat.S

**Comment by NorthernMan54** [comment]
There is no magic here, I'm just using an undocumented interface on Alexa to talk to HomeBridge.  I think everyone has seen the published documentation for creating a home skill with Alexa and how it uses cloud API's to interface with your device, but what is not published is that Alexa also has a local API that avoids the cloud.

If you have a Philips hue hub, Alexa can interface to it directly via your local network, and what I did was tap into this interface, and have homebridge emulate a hue v1 hub.  The communications are between your Alexa device and homebridge, no usage of the cloud, and uses the hue API.

With my first attempt, I used the home skill API, and had poked a hole in my firewall for communications but I abandoned this due to the complexity of configuration.

**Comment by svenkat86** [comment]
Thank you for this excellent detailed response. As you have mentioned,I am not finding much articles on the web for local API methods implementation. There is one by fauxmo using php fully, but am looking at something like your implementation on node ja. With this clarification, I am now trying to understand your code by reverse engineering it. My goal is to remove all HomeKit dependencies and Understand the simple Alexa-hue switch communication and working, so I can think about adding additional accesory support in future (like music player support, thermostat etc)

Thanks again,
Venkat.S

**Comment by NorthernMan54** [comment]
I have looked at adding other device types, as I have created a significant number of plugins, but this API has limited functionality.    As far as I'm aware it only supports on/off and dimming.  If it did support thermostats etc I would have mapped it.  For documentation, I used the Philips hue bridge API documentation as a base.

For music players, I have a Yamaha receiver and am using that with Alexa.  I modified the plugin so that the volume control mimics a light bulb.  And I just tell Alexa to change the brightness, and she changes the volume.

**Comment by svenkat86** [comment]
I am sure you would have definitely looked into the options of expanding this for other accessories. Just that I am curious on the working principle. I am still trying to figure out where the logic for local API exists. 
1) how are you able to make your accesory discoverable when Alexa searches? Is it that upnp or how it's done?
2) how is the turn on turn off requests made? Is it http? 

Also The folder aws got me confusing as it was applicable only for cloud API. 
Thanks.

**Comment by svenkat86** [comment]
I was able to find answers to my questions by comparing this design and the one by fauxmojs. 
Just wanted to post it here so it might help someone in future. 
Thank you.
