### ISSUE TITLE
All of a sudden I get an error :(

### ISSUE THREAD

**Issue by meluvalli** [NorthernMan54/homebridge-alexa#261]
ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README.

This just started!  I have been running it for months with no issues.  Nothing changed on my end.  Did something break?

**Comment by Venger2005** [comment]
Same thing happening here. After trying to deactivate and reactivate the Homebridge skill, I'm now unable to enable the skill via Alexa as it comes up with an error "We were unable to link Homebridge at this time."

**Comment by DJay-X** [comment]
Another voice here with the problem.
What a coincidence.  And I was worried because I factory reseted my iPhone and other iOS devices updated to iOS 13.2 Beta. Good to know that the homebridge-alexa issue has nothing to do with it.
Thanks for pointing to this issue which seems to be on the side of homebridge-alexa. 
But by this I'm feeling confident that @NorthernMan54 is fixing it soon. Thanks in advance.

**Comment by superpower10** [comment]
Same problem here. Alexa can't control my devices since about 2 hours ago.

**Comment by juliannof** [comment]
One more here with the same issue. Looks like something happened this morning as everything was working well early morning

**Comment by z-smoker** [comment]
I'll get in line....

**Comment by SzilagyiR** [comment]
Hi! Same problem here!

**Comment by MikeDeltaHH** [comment]
Same here since this morning...

**Comment by juliannof** [comment]
That’s the error I get from web page https://www.homebridge.ca/auth/finish

Error
    at SessionStore.load (/home/ubuntu/awsWeb/node_modules/oauth2orize/lib/txn/session.js:27:25)
    at transactionLoader (/home/ubuntu/awsWeb/node_modules/oauth2orize/lib/middleware/transactionLoader.js:42:24)
    at Layer.handle [as handle_request] (/home/ubuntu/awsWeb/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/awsWeb/node_modules/express/lib/router/route.js:137:13)
    at /home/ubuntu/awsWeb/index.js:520:9
    at Strategy.strategy.success (/home/ubuntu/awsWeb/node_modules/passport/lib/middleware/authenticate.js:201:18)
    at verified (/home/ubuntu/awsWeb/node_modules/passport-local/lib/strategy.js:83:10)
    at InternalFieldObject.ondone (/home/ubuntu/awsWeb/node_modules/passport-local-mongoose/lib/authenticate.js:48:16)

**Comment by cybersi** [comment]
Yup, me too! ;)

**Comment by manimac79** [comment]
me too...

**Comment by cvuzem** [comment]
me too :(

**Comment by orionn2o** [comment]
looks like homebridge.cloudwatch.net is down. 

i assume that causes the break?

**Comment by alonmalka** [comment]
Same here.

**Comment by networks514** [comment]
Same issue ... hope it’s a minor bug. Good luck

**Comment by swilalaa** [comment]
same here

**Comment by mrgingles** [comment]
Same here

**Comment by Nikse77** [comment]
same here

**Comment by zang74** [comment]
Yet another...

**Comment by thehauntedmattress** [comment]
Same here.  Not working.

**Comment by CoronaExtra** [comment]
Same problem. Worked 12 hours ago. Tried to unlink and link but not able to link it again.

**Comment by Marco1097** [comment]
Same here

**Comment by mickrz6** [comment]
Same here

**Comment by Sinthos** [comment]
Same here, suddenly stopped working a few hours ago.

**Comment by jnmarczi** [comment]
Same here.

**Comment by thhuss** [comment]
Same here

**Comment by NorthernMan54** [comment]
I reset the backend, please try again.  You may need to reset the plugin as well

**Comment by networks514** [comment]
Hi works again ! Many thanks 😊

**Comment by thehauntedmattress** [comment]
Working again here.  Thanks @NorthernMan54 .

**Comment by NorthernMan54** [comment]
Tks everyone for checking

**Comment by meluvalli** [comment]
Thank you!!!

**Comment by superbraz** [comment]
Works!
I activated the skill and restarted the homebridge

**Comment by z-smoker** [comment]
Thank you 🥇

**Comment by Nikse77** [comment]
Thank you!

**Comment by SzilagyiR** [comment]
Thanks!

**Comment by cybersi** [comment]
Thanks! 🙂

**Comment by mrgingles** [comment]
Thank you!

**Comment by mickrz6** [comment]
Working. Thanks

**Comment by juliannof** [comment]
Thank you!

**Comment by iomax** [comment]
> Tks everyone for checking

Hi @NorthernMan54 sorry if I'm boring you but since the error got few days ago as other people here showed, I'm not more able to get homebridge devices on "alexa" environment by your plugin. It worked since months when it suddenly it stop to work so I deleted all devices in alexa to try to resume it just before to discover it was an "central site" issue. The issue seems solved to most people now but unfortunately not in my case.
I can confirm that the showed error ( ERROR: ( homebridge-alexa) You have an issue with your installation, please review the README. ) is not more in the system logs but despite the plenty of all so standard or not,  tryed( homebridge instance restart, several restart of the dedicated homebridge-alexa instance, alexa homebridge skill removed and new add, lots of "find a new devices" by alexa environment up to the poweroff and restart of the platform that serve all of mine homebridge's instance ) "alexa" is still unable to find any more the devices coming by "homebridge". Let me to confirm one more time that this setup was up and running since months without any issues. Could you help me ? Any hints by your side ?

**Comment by NorthernMan54** [comment]
As this issue was resolved and closed, please open a new issue and supply a debug log from the plugin during device discovery

https://github.com/NorthernMan54/homebridge-alexa#debug-logs
