### ISSUE TITLE
Latest version, error

### ISSUE THREAD

**Issue by dcaccount** [NorthernMan54/homebridge-alexa#370]
Hello,
I have updated to latest version and it will not work. I get following error:

> [2020-10-4 17:41:31] [Alexa] PowerController TurnOn undefined undefined Error: ERROR: HB Instance not found

I tried to roll back from command line but home bridge is still on latest version and will not work.

Please help!
Thanks,
Dan

**Comment by NorthernMan54** [comment]
You will need to discover devices again

**Comment by dcaccount** [comment]
> You will need to discover devices again
> […](#)

Why, I have to redo all routine?

**Comment by NorthernMan54** [comment]
No you won’t, but the new version uses updated internal device identifiers  that are not compatible with the old version. Hence the error

**Comment by MatGriffin** [comment]
Same issue here. I've run discover devices but still not working.

**Comment by NorthernMan54** [comment]
@MatGriffin Made an update for an issue blocking another use, please update and try again.   If the issue continues, please open a new issue and attach logs in DEBUG mode.

**Comment by b2un0** [comment]
same here. Only #369 fixed the issue.
i made a rollback a few days ago and tried it today again with the theme problem..

```
[10/8/2020, 6:20:56 PM] [Alexa] alexaDiscovery - returned 58 devices
```

but In the [Alexa](https://alexa.amazon.de) WebUI i noticed, that every device shown twice

the old one as:
```
Wohnzimmer Deckenflutter 
Homebridge Wohnzimmer Deckenflutter Lightbulb
^
```

and  the new one as:
the old as
```
Wohnzimmer Deckenflutter 
homebridge Wohnzimmer Deckenflutter Lightbulb
^
```

as you can see, the small descriptor has `homedrige` writen in lowercase.

every old devices are not responding. the new devices must be attached again to each alexa group and routine..

[homebridge-alexa_0_5_12.log](https://github.com/NorthernMan54/homebridge-alexa/files/5349388/homebridge-alexa_0_5_12.log)

**Comment by NorthernMan54** [comment]
@b2un0 Unfortunately the latest version of homebridge causes a second set of devices to be created and the original devices need to be deleted.

**Comment by eos-uptrade** [comment]
this makes no sense.
if i downgrade to `homebridge-alexa@0.4.74` every existing device works!
According to your statement, the old `homebridge-alexa@0.4.74` version should also be broken with the latest homebridge version.

**Comment by b2un0** [comment]
this makes no sense.
if i downgrade to `homebridge-alexa@0.4.74` every existing device works!
According to your statement, the old `homebridge-alexa@0.4.74` version should also be broken with the latest homebridge version.

**Comment by NorthernMan54** [comment]
There are 2 separate recent changes one on the homebridge side and another on the homebridge-alexa side that you are seeing

1 - The problematic change that causes the duplicate devices was a change within Homebridge for the accessory signature to resolve a long standing issue with 'non responding' devices for everyone.  This was part of the 1.2.x update

2 -  A change with the version 0.5.x version of homebridge-alexa that fixes an issue with TV accessories not responding,  this changed the internal mapping to homebridge devices.  This update would not trigger duplicates, as only the internal mapping was enhanced.

So on the Alexa side, you have this

Accessories created from the v0.4.x Alexa version and the old homebridge version -> these devices only work with the 0.4.x plugin due to #2 the mapping change

Accessories created from the v0.5.x Alexa version and the new homebridge version -> these are duplicate devices due to #1, and only with the 0.5.x plugin due to #2

And with the 0.4.74 version of the plugin it will create duplicates with the 1.2.x version of homebridge.  But both the old and duplicate devices will work.

I realize that the duplicates are a pain, and I personally had to deal with a couple of hundred devices and the associated routines ;-(
