### ISSUE TITLE
Alexa wrong initialization

### ISSUE THREAD

**Issue by jannnfe** [NorthernMan54/homebridge-alexa#45]
Hello, I have been using this plugin for a while now, and it has served its purpose so far. Today I have set up a new Sonoff switch in my home, which is no longer recognized correctly. Likewise, a lamp is switched wrong. I say "wall lamp", but the "floor lamp" goes on and the "wall lamp" can not be switched on and off. Can I somehow delete the chache or something? Unfortunately, it is not possible to delete and re-teach all devices via the Alexa app. Thanks!

**Comment by NorthernMan54** [comment]
Ask Alexa to discover devices, and she will redo the cache.

**Comment by jannnfe** [comment]
The Problem is, of i ask to Discover New devices Alexa teils that there are no new devices and nothing changed. The Problem is still there. I dont have any idea to fix or resolve this :(

**Comment by pauleec** [comment]
Why can’t you just forget all the smart devices via the alexa app (Smart Home). Then ask Alexa to “Discover Devices”.

 

Regards

Paul Craton
+61411320255

**Comment by jannnfe** [comment]
It does not fix the issue. I deleted all Devices and discover them New and the same Problem is there. I dont know what i can do.

**Comment by NorthernMan54** [comment]
@jannnfe Okay I'm going to need a debug log to see into what is happening.  Can you restart homebridge with the DEBUG option, recreate the issue, and send me a copy of the output?

`DEBUG=* homebridge  2>&1 | tee debug.log`

Tks

**Comment by jannnfe** [comment]
This is my log asking alexa discovering new devices.
[debug.log](https://github.com/NorthernMan54/homebridge-alexa/files/1646549/debug.log)

**Comment by NorthernMan54** [comment]
Tks I have the log, and I think I see the issue.  I'm going to need to change my device numbering scheme for the linkage between alexa and homebridge.  As this is going to take a few days, you could try as a quick workaround, you could try deleting .homebridge/accessories and .homebridge/persistience and setup homebridge in Home again.

**Comment by jannnfe** [comment]
Nice thank you for looking into this issue. I have alredy deleted all files in the .homebridge folder except the config.json and Setting up homebridge againe. Now its working but i would love if you look into the issue to prevent this in the future :)
Thanks

**Comment by pauleec** [comment]
Hi,

I am happy to confirm that I now have a range of rgb colours and a range of
warm to cold white settings that can be applied with Alexa via the updated
homebridge-Alexa app.

Huge improvement on before!

I’ve included some screenshots of the Mi-Light app and how they handle both
white temperature and Color saturation. If the lights are not in a white
mode (ie where the W is not pressed/set to on), the RGB Color saturation
value can be set which allows for more pastel colours to be possible.

It’s really good work though.Alexa controls everything round my house now
:-)

One thing I noticed. The Color is set and is displayed in the Alexa app
light as the correct Color for about 10 seconds and then goes back to a
white.... is that normal?

I’ve included some screenshots of how the Alexa app shows the light zones
that are defined in the Mi-Light bridge I have setup here.

I am running the RM Tasker plugin as a way to expose my Broadlink-RM Pro
defined devices to Alexa and am starting to test the
homebridge-broadlink-rm plugin as an alternative and to remove the extra
android component (which runs the RM Tasker plugin). I’ll keep you posted
because initial tests of the way the new homebridge-alexa plugin open and
close the window coverings based on time per signal sent doesn’t seem to
work with the curtains I have here. (Rm Tasker sends a single open or close
signal rather than many signals) I’ll keep investigating.

Thanks again for this! Would you like me to send you a Mi-Light bridge and
a rgb-cut 8 zone cabable light for your own testing? If so send me your
mail address and I’ll post it to you.

All the best

Paul
