### ISSUE TITLE
Since v0.6.1 error HAP

### ISSUE THREAD

**Issue by xavierlp** [NorthernMan54/homebridge-alexa#561]
Hello 
After upgrade to the lastest version. I have this errro
ERROR: HAP Discovery failed, please review config

Same with MQTT, MQTTS , WSS

**Comment by NorthernMan54** [comment]
Resolved with 0.6.2 and #561

**Comment by cofresi59** [comment]
I am a newbie here, and I am trying to have my Wemo devices controlled by Alexa voice, and I get this error:
[Alexa] ERROR: HAP Discovery failed, please review config. The Alexa accessory is closed and on Apple Homekit says Alexa Contact Sensor is closed. I have no idea where to bewgin trouble shooting. I know that I was able to add the Wemo devices to Apple HomeKit through Homebridge with the Wemo plugin. Now, all I have to do is open the Alexa accessory to have Alexa control the devices via voice. Any help is deeply appreciated. I don't want to replace the Wemo devices since this will be a costly endeavor.

**Comment by NorthernMan54** [comment]
@cofresi59 pls open as a new issue, this is something else

Before opening a new issue, pls ensure that your wemo devices are visible in the accessories tab in the Homebridge UI
