### ISSUE TITLE
Silly question: Does V2 pass the wife/kids test?

### ISSUE THREAD

**Issue by JimBobSD** [NorthernMan54/homebridge-alexa#77]
First, love the plugin!  Second, I haven't updated to V2 yet.  So far, the V1 plugin works pretty well for my wife and kids.  However, before I make the jump to V2 - and potential endure the ire of "Dad, why did you break Alexa?" - does V2 work reliably as well as V1?  

Thanks!

**Comment by NorthernMan54** [comment]
Jim,

I showed your question to my wife, and she said it works as solidly as the previous version.  ( But I think she’s biased ). Look at the features of V2 and make your own choice, if you have colour bulbs or other devices supported by V2 then you should make the jump.  Over the next few months I will be adding features as incorporate more of the Alexa API.

PS only 1 reported issue since launch

**Comment by JimBobSD** [comment]
Thanks!  Let the upgrade begin!
