### ISSUE TITLE
Blacklist by Type

### ISSUE THREAD

**Issue by b2un0** [NorthernMan54/homebridge-alexa#80]
is there an option to black or whitelisting some types of devices?

eg:

i have a Hue Bridge with some third party devices for stripes and switches.
i'm also using `homebridge-hue`, after installation of `homebridge-alexa` all third party devices from hue are listed twice in Alexa.

Or is the `homebridge-hue` plugin now obsolete?

im suggestion: an array of whitelisting for types, eg.  "sensors" or blacklist for types, eg "lights".

**Comment by NorthernMan54** [comment]
Unfortunately there is no whitelisting or blacklisting feature at this time, but what you are looking for can be done by creating an instance of homebridge containing all the plugins you don’t want to expose via homebridge-Alexa and for that instance don’t add the -I option to the homebridge command line.

As this gets asked quite frequently I should really add a better explanation to the README, as a blacklisting plugins section.

For myself I use homebridge-hue and have not installed the Hue skill.

**Comment by jannnfe** [comment]
I also have this problem and it's a bit annoying because Alexa always asks which of the two devices I meant, since there are two with the same name.
The question I'm asking is why the homebridge-alexa plugin recognizes which lamps are really lamps from Philips and which are from another supplier via the homebridge-hue plugin.
Is there any other solution besides running a second Homebridge instance?
Thanks :)

**Comment by NorthernMan54** [comment]
Remove the Philips Hue skill from your Alexa configuration and just use homebridge-alexa.  That’s what I did in my setup.   Mind you I have the V1 hue hub, so it required resetting the hub back to factory as my configuration predated Alexa skill’s.

I did change the filter option recently, but now it filters based on homebridge instance which doesn’t help your situation.

If you wanted to improve the filter option, I would gladly accept a pull request.

**Comment by jannnfe** [comment]
I do not want to disable the skill, because otherwise I can not use the scenes of Hue Bridge. I will continue to live with the situation. I am so much thankful for the great plugin!
I do not think I can help you with a pull request. Maybe someday somebody else will find help to solve this problem.
Thank you for your work :)
